sonar.projectKey=jamesleonardgrijalbabolanos_BancoUdea
sonar.organization=jamesleonardgrijalbabolanos

sonar.java.source=17

sonar.python.version=3
sonar.sources=src/main/java,scripts
sonar.tests=src/test

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/*Test*.java,**/*IT*.java,**/target/**,**/*.feature
sonar.coverage.exclusions=**/*Application.java,**/*Config*.java
